# Generated by Django 3.1.5 on 2021-01-13 20:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MessageContent', models.CharField(max_length=512)),
                ('ExpirationSec', models.IntegerField(default=20)),
                ('CreationTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ReadingTime', models.DateTimeField()),
                ('IsRead', models.BooleanField(default=False)),
            ],
        ),
    ]
