# Generated by Django 3.1.5 on 2021-01-13 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecretMessageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretmessage',
            name='ReadingTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
